import type { Event } from '../../../types/index.js';

/** Demo events for Eventbrite fallback mode. */
export function getEventbriteDemoEvents(date: string): Event[] {
  const baseDate = date || new Date().toISOString().split('T')[0];
  return [
    {
      id: 'eb_demo_1',
      name: 'Jazz Night at Esplanade',
      description: 'An evening of smooth jazz performances featuring local and international artists at the iconic Esplanade.',
      category: 'concert',
      location: { name: 'Esplanade – Theatres on the Bay', address: '1 Esplanade Dr, Singapore 038981', lat: 1.2899, lng: 103.8556 },
      timeSlot: { start: `${baseDate}T19:00:00.000Z`, end: `${baseDate}T22:00:00.000Z` },
      price: { min: 25, max: 65, currency: 'SGD' },
      rating: 4.5,
      sourceUrl: 'https://www.eventbrite.sg/e/jazz-night-esplanade',
      source: 'eventbrite',
      availability: 'available',
      bookingRequired: true,
    },
    {
      id: 'eb_demo_2',
      name: 'Singapore Food Festival Street Market',
      description: 'Sample the best of Singapore street food at this outdoor festival featuring over 50 hawker stalls.',
      category: 'dining',
      location: { name: 'Clarke Quay', address: '3 River Valley Rd, Singapore 179024', lat: 1.2883, lng: 103.8467 },
      timeSlot: { start: `${baseDate}T11:00:00.000Z`, end: `${baseDate}T21:00:00.000Z` },
      price: { min: 0, max: 30, currency: 'SGD' },
      rating: 4.3,
      sourceUrl: 'https://www.eventbrite.sg/e/sg-food-festival',
      source: 'eventbrite',
      availability: 'available',
      bookingRequired: false,
    },
    {
      id: 'eb_demo_3',
      name: 'Night Photography Workshop',
      description: 'Learn night photography techniques in Marina Bay. Covers long exposure, light trails, and cityscape composition.',
      category: 'workshop',
      location: { name: 'Marina Bay Sands', address: '10 Bayfront Ave, Singapore 018956', lat: 1.2834, lng: 103.8607 },
      timeSlot: { start: `${baseDate}T18:30:00.000Z`, end: `${baseDate}T21:30:00.000Z` },
      price: { min: 45, max: 45, currency: 'SGD' },
      rating: 4.7,
      sourceUrl: 'https://www.eventbrite.sg/e/night-photography-workshop',
      source: 'eventbrite',
      availability: 'limited',
      bookingRequired: true,
    },
    {
      id: 'eb_demo_4',
      name: 'Gardens by the Bay Light Show',
      description: 'Experience the spectacular Garden Rhapsody light and sound show at the Supertree Grove.',
      category: 'outdoor',
      location: { name: 'Gardens by the Bay', address: '18 Marina Gardens Dr, Singapore 018953', lat: 1.2816, lng: 103.8636 },
      timeSlot: { start: `${baseDate}T19:45:00.000Z`, end: `${baseDate}T20:15:00.000Z` },
      price: { min: 0, max: 0, currency: 'SGD' },
      rating: 4.6,
      sourceUrl: 'https://www.eventbrite.sg/e/gardens-light-show',
      source: 'eventbrite',
      availability: 'available',
      bookingRequired: false,
    },
    {
      id: 'eb_demo_5',
      name: 'Rooftop Cocktail & DJ Session',
      description: 'Sunset drinks with panoramic views and live DJ spinning house and chill beats.',
      category: 'nightlife',
      location: { name: 'CÉ LA VI', address: '1 Bayfront Ave, Level 57, Singapore 018971', lat: 1.2838, lng: 103.8610 },
      timeSlot: { start: `${baseDate}T17:00:00.000Z`, end: `${baseDate}T23:00:00.000Z` },
      price: { min: 30, max: 80, currency: 'SGD' },
      rating: 4.4,
      sourceUrl: 'https://www.eventbrite.sg/e/rooftop-cocktail-dj',
      source: 'eventbrite',
      availability: 'available',
      bookingRequired: true,
    },
  ];
}

/** Demo events for EventFinda fallback mode. */
export function getEventfindaDemoEvents(date: string): Event[] {
  const baseDate = date || new Date().toISOString().split('T')[0];
  return [
    {
      id: 'ef_demo_1',
      name: 'Singapore Comedy Night',
      description: 'An evening of stand-up comedy featuring top local and international comedians at the Arts House.',
      category: 'theatre',
      location: { name: 'The Arts House', address: '1 Old Parliament Lane, Singapore 179429', lat: 1.2884, lng: 103.8508 },
      timeSlot: { start: `${baseDate}T19:30:00.000Z`, end: `${baseDate}T22:00:00.000Z` },
      price: { min: 25, max: 40, currency: 'SGD' },
      rating: 4.4,
      sourceUrl: 'https://www.eventfinda.sg/comedy-night',
      source: 'eventfinda',
      availability: 'available',
      bookingRequired: true,
    },
    {
      id: 'ef_demo_2',
      name: 'Artisan Craft Market @ Haji Lane',
      description: 'Browse unique handmade crafts, local art, and artisanal food at this vibrant street market.',
      category: 'exhibition',
      location: { name: 'Haji Lane', address: 'Haji Lane, Singapore 189241', lat: 1.3017, lng: 103.8593 },
      timeSlot: { start: `${baseDate}T10:00:00.000Z`, end: `${baseDate}T18:00:00.000Z` },
      price: { min: 0, max: 0, currency: 'SGD' },
      rating: 4.2,
      sourceUrl: 'https://www.eventfinda.sg/artisan-market',
      source: 'eventfinda',
      availability: 'available',
      bookingRequired: false,
    },
    {
      id: 'ef_demo_3',
      name: 'Sunset Yoga at Marina Barrage',
      description: 'Unwind with a relaxing sunset yoga session overlooking the Marina Bay skyline.',
      category: 'sports',
      location: { name: 'Marina Barrage', address: '8 Marina Gardens Dr, Singapore 018951', lat: 1.2808, lng: 103.8713 },
      timeSlot: { start: `${baseDate}T17:30:00.000Z`, end: `${baseDate}T19:00:00.000Z` },
      price: { min: 15, max: 15, currency: 'SGD' },
      rating: 4.6,
      sourceUrl: 'https://www.eventfinda.sg/sunset-yoga',
      source: 'eventfinda',
      availability: 'available',
      bookingRequired: true,
    },
    {
      id: 'ef_demo_4',
      name: 'Local Beats: Indie Music Showcase',
      description: 'Discover Singapore\'s best indie bands and solo artists at this intimate live music event.',
      category: 'concert',
      location: { name: 'Esplanade Annexe Studio', address: '1 Esplanade Dr, Singapore 038981', lat: 1.2899, lng: 103.8556 },
      timeSlot: { start: `${baseDate}T20:00:00.000Z`, end: `${baseDate}T23:00:00.000Z` },
      price: { min: 20, max: 35, currency: 'SGD' },
      rating: 4.5,
      sourceUrl: 'https://www.eventfinda.sg/indie-music',
      source: 'eventfinda',
      availability: 'limited',
      bookingRequired: true,
    },
    {
      id: 'ef_demo_5',
      name: 'Weekend Pottery Workshop',
      description: 'Hands-on pottery making for beginners. Create your own ceramic bowl or mug to take home.',
      category: 'workshop',
      location: { name: 'Thow Kwang Pottery Jungle', address: '85 Lorong Tawas, Singapore 639823', lat: 1.3312, lng: 103.7195 },
      timeSlot: { start: `${baseDate}T10:00:00.000Z`, end: `${baseDate}T13:00:00.000Z` },
      price: { min: 60, max: 80, currency: 'SGD' },
      rating: 4.7,
      sourceUrl: 'https://www.eventfinda.sg/pottery-workshop',
      source: 'eventfinda',
      availability: 'available',
      bookingRequired: true,
    },
  ];
}
